import FlamingoImage from '../assets/flamingo.jpg';
import WestinImage from '../assets/westin.jpg';

export const HOTELS = [
  {
    id: 1,
    name: 'The Flamingo',
    address: '3555 S Las Vegas Blvd, Las Vegas, NV 89109',
    phone: '(702) 733-3111',
    link: 'https://www.caesars.com/flamingo-las-vegas',
    image: FlamingoImage,
  },
  {
    id: 2,
    name: 'Westin',
    address: '160 E Flamingo Rd, Las Vegas, NV 89109',
    phone: '(702) 836-5900',
    link: 'https://www.marriott.com/en-us/hotels/lasvw-the-westin-las-vegas-hotel-and-spa/overview/',
    image: WestinImage,
  },
];
